In [1]:
from google.colab import files

uploaded = files.upload()

Saving e88186124ec611f1.zip to e88186124ec611f1.zip

In [2]:
import zipfile
zip_path = '/content/e88186124ec611f1.zip'
extract_to = '/content/gridlock_dataset'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_to)

print("Extraction complete.")

Extraction complete.

In [26]:
import pandas as pd

df = pd.read_csv('/content/gridlock_dataset/dataset/train.csv')
df.head()

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,48,0:0,0.048804,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,NaN,Rainy
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy

In [27]:
print(df.isnull().sum())

Index               0
geohash             0
day                 0
timestamp           0
demand              0
RoadType          600
NumberofLanes       0
LargeVehicles       0
Landmarks           0
Temperature      2495
Weather           797
dtype: int64

In [36]:
df_cleaned = df.dropna()
df_encoded = pd.get_dummies(df_cleaned, columns=['Weather'], prefix='Weather')
df_encoded.dropna(subset=['Temperature'], inplace=True)

In [37]:
df_encoded

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather_Foggy,Weather_Rainy,Weather_Snowy,Weather_Sunny
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,False,False,False,True
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,False,False,False,True
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,False,True,False,False
5,5,qp02zw,48,0:0,0.016262,Residential,2,Not Allowed,Yes,8.446025,False,True,False,False
6,6,qp02zy,48,0:0,0.042247,Residential,3,Allowed,Yes,15.772408,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77294,77294,qp0d4n,49,2:0,0.067203,Residential,1,Not Allowed,No,11.501664,False,True,False,False
77295,77295,qp0d4q,49,2:0,0.022859,Residential,3,Allowed,Yes,14.715254,True,False,False,False
77296,77296,qp0d4w,49,2:0,0.141342,Residential,3,Allowed,Yes,19.678860,False,False,False,True
77297,77297,qp0dhw,49,2:0,0.087574,Residential,1,Not Allowed,No,22.573958,False,False,False,True
77298,77298,qp0djq,49,2:0,0.002944,Residential,3,Allowed,Yes,1.322034,False,False,True,False

In [38]:
df_encoded = pd.get_dummies(df_encoded, columns=['RoadType'], prefix='Road')

In [39]:
df_encoded.head()

,Index,geohash,day,timestamp,demand,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather_Foggy,Weather_Rainy,Weather_Snowy,Weather_Sunny,Road_Highway,Road_Residential,Road_Street
1,1,qp02zt,48,0:0,0.118507,3,Allowed,Yes,31.104565,False,False,False,True,False,True,False
2,2,qp08bj,48,0:0,0.027132,1,Not Allowed,No,25.919267,False,False,False,True,False,True,False
4,4,qp02zq,48,0:0,0.010819,1,Not Allowed,No,10.803667,False,True,False,False,False,True,False
5,5,qp02zw,48,0:0,0.016262,2,Not Allowed,Yes,8.446025,False,True,False,False,False,True,False
6,6,qp02zy,48,0:0,0.042247,3,Allowed,Yes,15.772408,True,False,False,False,False,True,False

In [41]:
df_encoded['LargeVehicles'] = df_encoded['LargeVehicles'].map({'Allowed' : 1, 'Not Allowed' : 0})

Index                  21760
geohash               qp09hm
day                       48
timestamp               6:15
demand                0.0762
NumberofLanes              3
LargeVehicles            NaN
Landmarks                Yes
Temperature         17.37816
Weather_Foggy           True
Weather_Rainy          False
Weather_Snowy          False
Weather_Sunny          False
Road_Highway           False
Road_Residential        True
Road_Street            False
Name: 21760, dtype: object