In [16]:
from google.colab import files

uploaded = files.upload()

Saving e88186124ec611f1.zip to e88186124ec611f1.zip

In [17]:
import zipfile
zip_path = '/content/e88186124ec611f1.zip'
extract_to = '/content/gridlock2_dataset'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_to)

print("Extraction complete.")

Extraction complete.

In [22]:
import pandas as pd

df = pd.read_csv('/content/gridlock2_dataset/dataset/train.csv')
df.head()

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,48,0:0,0.048804,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,NaN,Rainy
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy

In [23]:
print(df.isnull().sum())

Index               0
geohash             0
day                 0
timestamp           0
demand              0
RoadType          600
NumberofLanes       0
LargeVehicles       0
Landmarks           0
Temperature      2495
Weather           797
dtype: int64

In [24]:
df_cleaned = df.dropna()
df_encoded = pd.get_dummies(df_cleaned, columns=['Weather'], prefix='Weather')
df_encoded.dropna(subset=['Temperature'], inplace=True)

In [25]:
df_encoded

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather_Foggy,Weather_Rainy,Weather_Snowy,Weather_Sunny
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,False,False,False,True
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,False,False,False,True
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,False,True,False,False
5,5,qp02zw,48,0:0,0.016262,Residential,2,Not Allowed,Yes,8.446025,False,True,False,False
6,6,qp02zy,48,0:0,0.042247,Residential,3,Allowed,Yes,15.772408,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77294,77294,qp0d4n,49,2:0,0.067203,Residential,1,Not Allowed,No,11.501664,False,True,False,False
77295,77295,qp0d4q,49,2:0,0.022859,Residential,3,Allowed,Yes,14.715254,True,False,False,False
77296,77296,qp0d4w,49,2:0,0.141342,Residential,3,Allowed,Yes,19.678860,False,False,False,True
77297,77297,qp0dhw,49,2:0,0.087574,Residential,1,Not Allowed,No,22.573958,False,False,False,True
77298,77298,qp0djq,49,2:0,0.002944,Residential,3,Allowed,Yes,1.322034,False,False,True,False

In [26]:
df_encoded = pd.get_dummies(df_encoded, columns=['RoadType'], prefix='Road')

In [27]:
df_encoded.head()

,Index,geohash,day,timestamp,demand,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather_Foggy,Weather_Rainy,Weather_Snowy,Weather_Sunny,Road_Highway,Road_Residential,Road_Street
1,1,qp02zt,48,0:0,0.118507,3,Allowed,Yes,31.104565,False,False,False,True,False,True,False
2,2,qp08bj,48,0:0,0.027132,1,Not Allowed,No,25.919267,False,False,False,True,False,True,False
4,4,qp02zq,48,0:0,0.010819,1,Not Allowed,No,10.803667,False,True,False,False,False,True,False
5,5,qp02zw,48,0:0,0.016262,2,Not Allowed,Yes,8.446025,False,True,False,False,False,True,False
6,6,qp02zy,48,0:0,0.042247,3,Allowed,Yes,15.772408,True,False,False,False,False,True,False

In [28]:
df_encoded['LargeVehicles'] = df_encoded['LargeVehicles'].map({'Allowed' : 1, 'Not Allowed' : 0})
df_encoded['Landmarks'] = df_encoded['Landmarks'].map({'Yes' : 1, 'No' : 0})

df_encoded

,Index,geohash,day,timestamp,demand,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather_Foggy,Weather_Rainy,Weather_Snowy,Weather_Sunny,Road_Highway,Road_Residential,Road_Street
1,1,qp02zt,48,0:0,0.118507,3,1,1,31.104565,False,False,False,True,False,True,False
2,2,qp08bj,48,0:0,0.027132,1,0,0,25.919267,False,False,False,True,False,True,False
4,4,qp02zq,48,0:0,0.010819,1,0,0,10.803667,False,True,False,False,False,True,False
5,5,qp02zw,48,0:0,0.016262,2,0,1,8.446025,False,True,False,False,False,True,False
6,6,qp02zy,48,0:0,0.042247,3,1,1,15.772408,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77294,77294,qp0d4n,49,2:0,0.067203,1,0,0,11.501664,False,True,False,False,False,True,False
77295,77295,qp0d4q,49,2:0,0.022859,3,1,1,14.715254,True,False,False,False,False,True,False
77296,77296,qp0d4w,49,2:0,0.141342,3,1,1,19.678860,False,False,False,True,False,True,False
77297,77297,qp0dhw,49,2:0,0.087574,1,0,0,22.573958,False,False,False,True,False,True,False
77298,77298,qp0djq,49,2:0,0.002944,3,1,1,1.322034,False,False,True,False,False,True,False

In [29]:
#decoding the geohash into latitude and longitude
!pip install pygeohash

Collecting pygeohash
  Downloading pygeohash-3.3.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (11 kB)
Downloading pygeohash-3.3.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.3/44.3 kB 4.1 MB/s eta 0:00:00
Installing collected packages: pygeohash
Successfully installed pygeohash-3.3.0

In [31]:
import pygeohash as pgh

df_encoded['latitude'] = None
df_encoded['longitude'] = None

def decode_geohash(geohash_string):
  if pd.isna(geohash_string) or geohash_string == '':
    return None, None
  else:
    return pgh.decode(geohash_string)


df_encoded[['latitude', 'longitude']] = df_encoded['geohash'].apply(lambda x : pd.Series(decode_geohash(x)))

In [32]:
df_encoded

,Index,geohash,day,timestamp,demand,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather_Foggy,Weather_Rainy,Weather_Snowy,Weather_Sunny,Road_Highway,Road_Residential,Road_Street,latitude,longitude
1,1,qp02zt,48,0:0,0.118507,3,1,1,31.104565,False,False,False,True,False,True,False,-5.462952,90.686646
2,2,qp08bj,48,0:0,0.027132,1,0,0,25.919267,False,False,False,True,False,True,False,-5.462952,90.708618
4,4,qp02zq,48,0:0,0.010819,1,0,0,10.803667,False,True,False,False,False,True,False,-5.457458,90.675659
5,5,qp02zw,48,0:0,0.016262,2,0,1,8.446025,False,True,False,False,False,True,False,-5.457458,90.686646
6,6,qp02zy,48,0:0,0.042247,3,1,1,15.772408,True,False,False,False,False,True,False,-5.457458,90.697632
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77294,77294,qp0d4n,49,2:0,0.067203,1,0,0,11.501664,False,True,False,False,False,True,False,-5.237732,90.796509
77295,77295,qp0d4q,49,2:0,0.022859,3,1,1,14.715254,True,False,False,False,False,True,False,-5.237732,90.807495
77296,77296,qp0d4w,49,2:0,0.141342,3,1,1,19.678860,False,False,False,True,False,True,False,-5.237732,90.818481
77297,77297,qp0dhw,49,2:0,0.087574,1,0,0,22.573958,False,False,False,True,False,True,False,-5.237732,90.906372
77298,77298,qp0djq,49,2:0,0.002944,3,1,1,1.322034,False,False,True,False,False,True,False,-5.237732,90.939331

In [33]:
df_encoded = df_encoded.drop(columns = ['geohash'])

In [34]:
df_encoded.head()

,Index,day,timestamp,demand,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather_Foggy,Weather_Rainy,Weather_Snowy,Weather_Sunny,Road_Highway,Road_Residential,Road_Street,latitude,longitude
1,1,48,0:0,0.118507,3,1,1,31.104565,False,False,False,True,False,True,False,-5.462952,90.686646
2,2,48,0:0,0.027132,1,0,0,25.919267,False,False,False,True,False,True,False,-5.462952,90.708618
4,4,48,0:0,0.010819,1,0,0,10.803667,False,True,False,False,False,True,False,-5.457458,90.675659
5,5,48,0:0,0.016262,2,0,1,8.446025,False,True,False,False,False,True,False,-5.457458,90.686646
6,6,48,0:0,0.042247,3,1,1,15.772408,True,False,False,False,False,True,False,-5.457458,90.697632

In [36]:
df_encoded.to_csv('/content/gridlock2_dataset/dataset/cleaned_data.csv', index=False)